//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int AccessoriesID { get; set; }
        public string AccessoriesName { get; set; }
        public string AccessoriesPhoto { get; set; }
        public string AccessoriesType { get; set; }
        public string AccessoriesColor { get; set; }
        public string AccessoriesSeason { get; set; }
        public string AccessoriesOccasion { get; set; }
    }
}
